trigger:
  branches:
    include:
      - main

pool: 'new-self-hosted-pool'

steps:
  - checkout: self
  
  - task: ArchiveFiles@2
    inputs: 
      rootFolderOrFile: '/myagent/$(Build.SourcesDirectory)'
      includeRootFolder: false
      archiveType: 'zip'
      archiveFile: '/myagent/$(Build.ArtifactStagingDirectory)/XYZ.zip'
  
  - task: Bash@3
    inputs:
      script: |
        pwd
  - task: SSH@0
    inputs:
      sshEndpoint:  'VM-connection'
      runOptions: 'commands'
      commands: |
        scp $/myagent/(Build.ArtifactStagingDirectory)/XYZ.zip azureuser@20.51.192.206:/home/azureuser
      