trigger:
  branches:
    include:
      - main

pool: 'new-self-hosted-pool'

steps:
  - checkout: self
  - task: ArchiveFiles@2
    inputs: 
      rootFolderOrFile: '$(Build.SourcesDirectory)'
      includeRootFolder: false
      archiveType: 'zip'
      archiveFile: '$(Build.ArtifactStagingDirectory)/XYZ.zip'
  - task: SSH@0
    inputs:
      sshEndpoint:  'VM-connection'
      runOptions: 'commands'
      commands: |
        scp $(Build.ArtifactStagingDirectory)/XYZ.zip azureuser@20.51.192.206:/ubuntu/home
      