trigger:
  branches:
    include:
      - main

pool: 'new-self-hosted-pool'

steps:
  - checkout: self
  
  - task: Bash@3
    inputs:
      targetType: inline
      script: |
        cd $(Build.SourcesDirectory)
        ls
        pwd
  - task: ArchiveFiles@2
    inputs: 
      rootFolderOrFile: '$(Build.SourcesDirectory)'
      includeRootFolder: false
      archiveType: 'tar'
      archiveFile: '$(Build.ArtifactStagingDirectory)/XYZ.tar.gz'
  
  - task: SSH@0
    inputs:
      sshEndpoint:  'VM-connection'
      runOptions: 'commands'
      commands: |
        ssh-keyscan -H 20.51.192.206 >> ~/.ssh/known_hosts
        scp $(Build.ArtifactStagingDirectory)/XYZ.tar.gz azureuser@20.51.192.206:/home/azureuser
      