
name:  CICD Deployment
on:
  push:
    branches:
      -  main

  pull_request:
    branches:
      -  main

  schedule:
    -  cron:  '0 0 * * *'

  release:
    types:
      -  published
      -  created
      -  prereleased
jobs:
  deploy:
    runs-on:  ubuntu-latest
    steps:
      - name:  Update EC2
        run:  |
            sudo apt update

      - name:  Print names
        run:  |
            echo "Ishwari"

      - name:  Current folder
        run:  |
            pwd
            
    
